dist: trusty
language: go

env:
  COMPOSE_VERSION: 1.24.1

before_install:
  # Docker Compose Install 
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv --force docker-compose /usr/local/bin

script:
- docker-compose build cli
- docker cp apollo-devops_cli_1:/usr/local/go/src/github.com/brave-experiments/apollo-devops/apollo

before_deploy:
- git config --local user.name "TravisCI"
- git config --local user.email "devnull@brave.com"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: KvvrZg7BaEnSC04Be3V0tXSJ7OuZ338gDVSQyY7jtABZgfUQWDQrS385f4ricr/PwKtyrU0Nt5LPPp0Jz0WFtIXKr4TNZeNqwlwmbegi6S+kTpWd7Oi2TTLJqt3Z7MaoqVDSlm4jSBrH5Nvs9MWzvCQ8h+XVUWZJk0yeGiF3JxZDr6UX+WiBYvaDrXc2xwXXG0OLgmnEw13Ima4fLOhYXuIppi+7CRFMbcyxDpZREShldt2i58lRhSFFJSE1C+TT4b87mR+s+7suC3gC9ql/WaLQqet25DJrxX8Ax/7osVbXM8EGvty8c3es7OTXnqoiAIvd5d0w0Sd5PXfYS60Cu5goEE0CHcYdB6w3v7NrWt0cRPrf1AqHb7AD+aw0lLPtwUIZA+xBFstW4+nr4huPrDA49Y5yR7G3+qxBq9XlRpqHDTOrsby1aTlxdMRPJzT0nqSKFLmPk2MkQGtmgAJHvyb9eSxrjSzdIJcz4jJ/IOVxp3q/mcyTih6dCaOl57sA1aGRyUfHRN0YeejCFwA9vV/2lbGfplrcQ1Jr0VNT4KkY3FHtxhHkOR57+pUi8boedsFcT+sbGdFYAuQDfFM2fFIfJnFkcFH63ezpyBxqs9OaDM/Ecv/5xfyYaCRZuUn/u7LquDSUVKE4EJbpH5g6JZ9mppRtFPNngHouVbhzRyU=
  file: apollo
  on:
    repo: brave-experiments/apollo-devops

