[parity]
chain = "/var/config/genesis.json"
base_path = "/var/app"
[network]
port = 30303
[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8456
#[account]
#password = ["node.pwds"]
#[mining]
#engine_signer = "0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e"
#reseal_on_txs = "none"