version: '3.6'
services:
  node1:
    image: parity/parity
    networks:
      - parity
    ports:
      - 30304:30303
      - 8546:8545
    command: ["$PARITY_BOOTSTRAP_PROPERTIES"]
    volumes:
      - ./node1:/var/app
    env_file:
      - .env

  node2:
    image: parity/parity
    networks:
      - parity
    ports:
      - 30305:30303
      - 8547:8545
    command: ["$PARITY_BOOTSTRAP_PROPERTIES"]
    volumes:
      - ./node2:/var/app
    env_file:
      - .env

  cli:
    image: apollo-ubuntu
    build: ./.docker/ubuntu
    networks:
      - parity
    volumes:
      - ./ubuntu:/var/app
    env_file:
      - .env

networks:
  parity:
    driver: bridge