version: '3.6'
services:
  node1:
    build: .docker/parity
    image: apollo-parity
    user: root
    networks:
      - parity
    ports:
      - 30304:30303
      - 8540:8545
      - 8550:8546
    volumes:
      - ./.docker/parity/config:/var/config
    command: ["$PARITY_BOOTSTRAP_PROPERTIES_NODE1", "--unsafe-expose"]
    env_file:
      - .env

  node2:
    build: .docker/parity
    image: apollo-parity
    user: root
    networks:
      - parity
    ports:
      - 30305:30303
      - 8541:8545
      - 8551:8546
    volumes:
      - ./.docker/parity/config:/var/config
    command: ["$PARITY_BOOTSTRAP_PROPERTIES_NODE2", "--unsafe-expose"]
    env_file:
      - .env

  cli:
    image: apollo-ubuntu
    build: ./.docker/ubuntu
    networks:
      - parity
    volumes:
      - ./ubuntu:/var/app
    env_file:
      - .env

networks:
  parity:
    driver: bridge