version: '3.6'
services:
  node0:
    build: .docker
    image: apollo-parity
    user: root
    networks:
      - parity
    ports:
      - 30304:30303
      - 8540:8545
      - 8550:8546
    volumes:
      - ./.docker/config:/var/config
    command: [
      "$PARITY_BOOTSTRAP_PROPERTIES_NODE0",
      "--unsafe-expose",
      "account",
      "new",
      "$PARITY_PASSWORD_LOCATION"
    ]
    env_file:
      - .env

  node1:
    build: .docker
    image: apollo-parity
    user: root
    networks:
      - parity
    ports:
      - 30304:30303
      - 8540:8545
      - 8550:8546
    volumes:
      - ./.docker/config:/var/config
    command: ["$PARITY_BOOTSTRAP_PROPERTIES_NODE1", "--unsafe-expose"]
    env_file:
      - .env

  node2:
    build: .docker
    image: apollo-parity
    user: root
    networks:
      - parity
    ports:
      - 30305:30303
      - 8541:8545
      - 8551:8546
    volumes:
      - ./.docker/config:/var/config
    command: ["$PARITY_BOOTSTRAP_PROPERTIES_NODE2", "--unsafe-expose"]
    env_file:
      - .env

  cli:
    image: apollo-parity
    build: ./.docker
    user: root
    entrypoint: ["/bin/bash"]
    networks:
      - parity
    volumes:
      - ./ubuntu:/var/app
    env_file:
      - .env

networks:
  parity:
    driver: bridge